# Framework for running automated tests on OSB using Travis-CI, see https://github.com/OpenSourceBrain/osb-model-validation

dist: xenial
sudo: false

addons:
  apt:
    packages:
       # Requirements for Brian
    - python-numpy 
    - python-scipy 
    - python-matplotlib 
    - python-sympy
    
language: python
python: 2.7

virtualenv:
    system_site_packages: true
    
env:
    - OMV_ENGINE=jLEMS
install: 
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation
    - pip install pandas
    - pip install tellurium

script:
    - omv all -V
    - pwd
    - ls -alt
    - ls -alt LEMS
    - omv list -V
    - cd SBML
    - python test_tellurium.py
    
    
    

