# Framework for running automated tests on OSB using Travis-CI, see https://github.com/OpenSourceBrain/osb-model-validation

dist: xenial
sudo: false 

language: python
python: 2.7

env:
    - OMV_ENGINE=jLEMS
    - OMV_ENGINE=PyLEMS
    - OMV_ENGINE=jNeuroML
    - OMV_ENGINE=PyLEMS_NeuroML2
    - OMV_ENGINE=jNeuroML_NEURON
install: 
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation

script:
    - omv all -V
    - pwd
    - ls -alt
    - ls -alt LEMS
    - omv list -V
    
    
    

