[project]
name = "SBMLShowcase"
dynamic = ["version"]
requires-python = ">=3.9"
dependencies = [
    "airspeed==0.6.0",
    "annotated-types==0.6.0",
    "antimony==2.14.0",
    "appdirs==1.4.4",
    "asttokens==2.4.1",
    "attrs==23.2.0",
    "blosc2==2.6.2",
    "cachetools==5.3.3",
    "cattrs==23.2.3",
    "certifi==2024.2.2",
    "cfgv==3.4.0",
    "chardet==5.2.0",
    "charset-normalizer==3.3.2",
    "colorama==0.4.6",
    "comm==0.2.2",
    "contourpy==1.2.1",
    "cycler==0.12.1",
    "debugpy==1.8.1",
    "decorator==5.1.1",
    "depinfo==2.2.0",
    "dill==0.3.8",
    "distlib==0.3.9",
    "dnspython==2.6.1",
    "docker==7.0.0",
    "docstring_parser==0.16",
    "executing==2.0.1",
    "fastobo==0.12.3",
    "filelock==3.16.1",
    "fonttools==4.51.0",
    "graphviz==0.20.3",
    "h5py==3.11.0",
    "identify==2.6.3",
    "idna==3.7",
    "iniconfig==2.0.0",
    "ipykernel==6.29.4",
    "ipython==8.24.0",
    "isodate==0.6.1",
    "jedi==0.19.1",
    "Jinja2==3.1.3",
    "jupyter_client==8.6.1",
    "jupyter_core==5.7.2",
    "kiwisolver==1.4.5",
    "libNeuroML==0.5.8",
    "libroadrunner==2.6.0",
    "lxml==5.2.1",
    "markdown-it-py==3.0.0",
    "MarkupSafe==2.1.5",
    "matplotlib==3.9.2",
    "matplotlib-inline==0.1.7",
    "matplotlib-scalebar==0.8.1",
    "mdurl==0.1.2",
    "modelspec==0.3.4",
    "mpmath==1.3.0",
    "msgpack==1.0.8",
    "natsort==8.4.0",
    "ndindex==1.8",
    "nest-asyncio==1.6.0",
    "networkx==3.3",
    "neuromllite==0.5.9",
    "nodeenv==1.9.1",
    "numexpr==2.10.0",
    "numpy==1.26.4",
    "packaging==24.0",
    "pandas==2.2.2",
    "parso==0.8.4",
    "phrasedml==1.3.0",
    "pillow==10.3.0",
    "platformdirs==4.2.1",
    "plotly==5.22.0",
    "pluggy==1.5.0",
    "ppft==1.7.6.8",
    "pre_commit==4.0.1",
    "progressbar2==4.5.0",
    "prompt-toolkit==3.0.43",
    "pronto==2.5.7",
    "psutil==5.9.8",
    "pure-eval==0.2.2",
    "py-cpuinfo==9.0.0",
    "pydantic==2.7.1",
    "pydantic_core==2.18.2",
    "Pygments==2.17.2",
    "PyLEMS==0.6.7",
    "pymetadata==0.4.2",
    "pymongo==4.7.1",
    "pyNeuroML==1.3.12",
    "pyparsing==3.1.2",
    "pytest==8.2.0",
    "python-dateutil==2.9.0.post0",
    "python-libcombine==0.2.20",
    "python-libnuml==1.1.6",
    "python-libsbml==5.20.2",
    "python-libsedml==2.0.32",
    "python-utils==3.9.0",
    "pytz==2024.1",
    "pywin32==306",
    "PyYAML==6.0.1",
    "pyzmq==26.0.2",
    "rdflib==7.0.0",
    "requests==2.31.0",
    "requests-file==2.0.0",
    "requests-toolbelt==1.0.0",
    "rich==13.7.1",
    "rrplugins==2.6.0",
    "scipy==1.13.0",
    "six==1.16.0",
    "stack-data==0.6.3",
    "sympy==1.12",
    "tables==3.9.2",
    "tabulate==0.9.0",
    "tellurium==2.2.10",
    "tenacity==8.2.3",
    "tornado==6.4",
    "traitlets==5.14.3",
    "typing_extensions==4.11.0",
    "tzdata==2024.1",
    "urllib3==2.2.1",
    "virtualenv==20.28.0",
    "vulture==2.13",
    "wcwidth==0.2.13",
    "xmltodict==0.13.0",
    "zeep==4.2.1"
]

[build-system]
requires = ["setuptools>=42", "wheel", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = { find = { include = ["utils"] } }