
[project]
name = "SBMLShowcase"
dynamic = ["version"]
requires-python = ">=3.9"

dependencies = [
    "pre-commit",
    "pyNeuroML[annotations]",
    "python-libsedml",
    "pytest",
    "tellurium",
    "pymetadata>=0.4.2",
    "docker",
    "requests<2.32.0",
]


[build-system]
requires = ["setuptools>=42", "wheel", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = { find = { include = ["utils"] } }
